language: node_js

node_js:
  - "10.15.3"
  # - "12"

services:
  - docker

install:
  - npm i

script:
  # - npm run services:start
  # - npm run services:healthcheck
  # - npm run lint
  # - npm run test:contracts
  - npm run test
  # - npm run codecov
  # - npm run services:stop
