language: node_js
node_js:
  - "10.15.3"

cache:
  directories:
    - "node_modules"

install:
  - npm i
  - npm run bootstrap

script:
  - npm run create-local-runtimeconfig
  - npm run test:contracts
  - npm run contracts:migrate:dev
  - npm run lint
  - npm run coverage
  - npm run codecov
