language: node_js

node_js:
  - "10.15.3"

services:
  - docker

before_install:
  - docker run -p 5984:5984 -d couchdb

install:
  - npm i

script:
  - npm run services:start
  - npm run services:healthcheck
  - npm run lint
  - npm run test:contracts
  - npm run coverage
  - npm run codecov
  - npm run services:stop
