language: node_js
node_js:
  - "10.15.3"

cache:
  directories:
    - "node_modules"

install:
  - npm i

script:
  - npm run services:start
  - npm run services:healthcheck
  # - npm run test:contracts
  # - npm run coverage
  # - npm run codecov
  - npm run services:stop
