version: '3.7'

services:
  element-app:
    container_name: element-app
    build:
      context: ./packages/element-app
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'

  element-api:
    container_name: element-api
    build: ./packages/element-api
    command: npm run start:express
    ports:
      - '5002:5002'
    volumes:
      - .:/srv/element-api
      - element-api_node_modules:/srv/element-api/node_modules

volumes:
  element-api_node_modules:
