version: '3.7'

services:
  element-api:
    build: .
    command: npm run start:express
    ports:
      - '5002:5002'
    volumes:
      - .:/srv/element-api
      - element-api_node_modules:/srv/element-api/node_modules

volumes:
  element-api_node_modules:
